const email =
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
+ '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">'
+ '<head>'
+ '<!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->'
+ '<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>'
+ '<meta content="width=device-width" name="viewport"/>'
+ '<!--[if !mso]><!-->'
+ '<meta content="IE=edge" http-equiv="X-UA-Compatible"/>'
+ '<!--<![endif]-->'
+ '<title></title>'
+ '<!--[if !mso]><!-->'
+ '<!--<![endif]-->'
+ '<style type="text/css">'
+ '		body {'
+ '			margin: 0;'
+ '			padding: 0;'
+ '		}'
+ '		table,'
+ '		td,'
+ '		tr {'
+ '			vertical-align: top;'
+ '			border-collapse: collapse;'
+ '		}'
+ '		* {'
+ '			line-height: inherit;'
+ '		}'
+ '		a[x-apple-data-detectors=true] {'
+ '			color: inherit !important;'
+ '			text-decoration: none !important;'
+ '		}'
+ '	</style>'
+ '<style id="media-query" type="text/css">'
+ '		@media (max-width: 720px) {'
+ '			.block-grid,'
+ '			.col {'
+ '				min-width: 320px !important;'
+ '				max-width: 100% !important;'
+ '				display: block !important;'
+ '			}'
+ '			.block-grid {'
+ '				width: 100% !important;'
+ '			}'
+ '			.col {'
+ '				width: 100% !important;'
+ '			}'
+ '			.col_cont {'
+ '				margin: 0 auto;'
+ '			}'
+ '			img.fullwidth,'
+ '			img.fullwidthOnMobile {'
+ '				max-width: 100% !important;'
+ '			}'
+ '			.no-stack .col {'
+ '				min-width: 0 !important;'
+ '				display: table-cell !important;'
+ '			}'
+ '			.no-stack.two-up .col {'
+ '				width: 50% !important;'
+ '			}'
+ '			.no-stack .col.num2 {'
+ '				width: 16.6% !important;'
+ '			}'
+ '			.no-stack .col.num3 {'
+ '				width: 25% !important;'
+ '			}'
+ '			.no-stack .col.num4 {'
+ '				width: 33% !important;'
+ '			}'
+ '			.no-stack .col.num5 {'
+ '				width: 41.6% !important;'
+ '			}'
+ '			.no-stack .col.num6 {'
+ '				width: 50% !important;'
+ '			}'
+ '			.no-stack .col.num7 {'
+ '				width: 58.3% !important;'
+ '			}'
+ '			.no-stack .col.num8 {'
+ '				width: 66.6% !important;'
+ '			}'
+ '			.no-stack .col.num9 {'
+ '				width: 75% !important;'
+ '			}'
+ '			.no-stack .col.num10 {'
+ '				width: 83.3% !important;'
+ '			}'
+ '			.video-block {'
+ '				max-width: none !important;'
+ '			}'
+ '			.mobile_hide {'
+ '				min-height: 0px;'
+ '				max-height: 0px;'
+ '				max-width: 0px;'
+ '				display: none;'
+ '				overflow: hidden;'
+ '				font-size: 0px;'
+ '			}'
+ '			.desktop_hide {'
+ '				display: block !important;'
+ '				max-height: none !important;'
+ '			}'
+ '		}'
+ '	</style>'
+ '</head>'
+ '<body class="clean-body" style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%; background-color: #ffffff;">'
+ '<!--[if IE]><div class="ie-browser"><![endif]-->'
+ '<table bgcolor="#ffffff" cellpadding="0" cellspacing="0" class="nl-container" role="presentation" style="table-layout: fixed; vertical-align: top; min-width: 320px; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td style="word-break: break-word; vertical-align: top;" valign="top">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="background-color:#ffffff"><![endif]-->'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;background-image:url("images/backgound_test.png");background-position:top left;background-repeat:no-repeat">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#f3eee8;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="20" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 20px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="20" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/logo_design.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 140px; display: block;" title="Alternate text" width="140"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="10" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 10px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="10" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.2; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 14px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 17px; margin: 0;"><strong><span style="font-size: 42px;">Episode <u>12</u></span></strong></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.2; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 42px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 50px; margin: 0;"><span style="font-size: 42px;">James Franco</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="5" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 5px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="5" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<div align="center" class="img-container center autowidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center autowidth" src="images/Play_Button_2.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 100px; display: block;" title="Alternate text" width="100"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 30px; padding-left: 30px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:30px;padding-bottom:10px;padding-left:30px;">'
+ '<div style="line-height: 1.5; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">'
+ '<p style="font-size: 18px; line-height: 1.5; word-break: break-word; text-align: center; mso-line-height-alt: 27px; margin: 0;"><span style="font-size: 18px;">Play Here</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="5" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 5px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="5" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.5; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">'
+ '<p style="font-size: 18px; line-height: 1.5; word-break: break-word; text-align: center; mso-line-height-alt: 27px; margin: 0;"><span style="font-size: 18px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/middle_Image_2.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 455px; display: block;" title="Alternate text" width="455"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.5; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">'
+ '<p style="font-size: 17px; line-height: 1.5; word-break: break-word; text-align: center; mso-line-height-alt: 26px; mso-ansi-font-size: 18px; margin: 0;"><span style="font-size: 17px; mso-ansi-font-size: 18px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, se. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#f3eee8;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 01px solid #ABABAB; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#f3eee8;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.2; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 18px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 22px; margin: 0;"><span style="font-size: 18px;">Previous Episode</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid three-up" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="233" style="background-color:#f3eee8;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="233" style="background-color:#f3eee8;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center autowidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center autowidth" src="images/Rectangle.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 10px; display: block;" title="Alternate text" width="10"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="233" style="background-color:#f3eee8;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#f3eee8;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 20px; padding-left: 20px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.2; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 42px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 50px; margin: 0;"><span style="font-size: 42px;">5 Steps to Client Winning Design</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="0" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 0px; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="0" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f3eee8;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#f3eee8;background-image:url("images/light_background.png");background-position:top left;background-repeat:no-repeat">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#f3eee8"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#f3eee8;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:0px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center fixedwidth fullwidthOnMobile" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth fullwidthOnMobile" src="images/coffee_and_headphone.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 420px; display: block;" title="Alternate text" width="420"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #e8edf3;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e8edf3;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#e8edf3"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#e8edf3;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="15" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 15px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="15" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 30px; padding-left: 30px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:30px;padding-bottom:10px;padding-left:30px;">'
+ '<div style="line-height: 1.5; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">'
+ '<p style="font-size: 14px; line-height: 1.5; word-break: break-word; text-align: center; mso-line-height-alt: 21px; margin: 0;"><strong><span style="font-size: 18px;">Subscribe and leave us review</span></strong></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 20px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.5; font-size: 12px; color: #393d47; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">'
+ '<p style="font-size: 18px; line-height: 1.5; word-break: break-word; text-align: center; mso-line-height-alt: 27px; margin: 0;"><span style="font-size: 18px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</span></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid four-up no-stack" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #e8edf3;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e8edf3;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#e8edf3"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="175" style="background-color:#e8edf3;width:175px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num3" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 174px; width: 175px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/pocket_cast.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 131px; display: block;" title="Alternate text" width="131"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="175" style="background-color:#e8edf3;width:175px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num3" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 174px; width: 175px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/apple_podcast.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 122px; display: block;" title="Alternate text" width="122"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="175" style="background-color:#e8edf3;width:175px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num3" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 174px; width: 175px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/google_podcast.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 122px; display: block;" title="Alternate text" width="122"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="175" style="background-color:#e8edf3;width:175px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num3" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 174px; width: 175px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;">'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr style="line-height:0px"><td style="padding-right: 0px;padding-left: 0px;" align="center"><![endif]--><img align="center" alt="Alternate text" border="0" class="center fixedwidth" src="images/spotify_logo.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 122px; display: block;" title="Alternate text" width="122"/>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '</div>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #e8edf3;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e8edf3;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#e8edf3"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#e8edf3;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 01px solid #ABABAB; width: 95%;" valign="top" width="95%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="15" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 15px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="15" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid three-up" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #e8edf3;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e8edf3;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#e8edf3"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="233" style="background-color:#e8edf3;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.2; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #393d47; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 19px; margin: 0;"><strong>Links</strong></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 20px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#656565;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.8;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:20px;">'
+ '<div style="line-height: 1.8; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #656565; mso-line-height-alt: 22px;">'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;">All Episodes</p>'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;"><a href="#" rel="noopener" style="text-decoration: none; color: #656565;" target="_blank">Help Center</a></p>'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;"><a href="#" rel="noopener" style="text-decoration: none; color: #656565;" target="_blank">Tour Guide</a></p>'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;"><a href="#" rel="noopener" style="text-decoration: none; color: #656565;" target="_blank"></a></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="233" style="background-color:#e8edf3;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.2; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #393d47; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 19px; margin: 0;"><strong>Contact Info</strong></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#656565;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.8;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.8; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #656565; mso-line-height-alt: 22px;">'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;">UK (+23) 456 7890 <br/>US (+22) 456 7891</p>'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;"> </p>'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;">support@domain.com <br/>sales@domain.com</p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td><td align="center" width="233" style="background-color:#e8edf3;width:233px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num4" style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 232px; width: 233px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#393d47;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.2; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #393d47; mso-line-height-alt: 14px;">'
+ '<p style="font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 19px; margin: 0;"><strong>Company Name</strong></p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Tahoma, sans-serif"><![endif]-->'
+ '<div style="color:#656565;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.8;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">'
+ '<div style="line-height: 1.8; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #656565; mso-line-height-alt: 22px;">'
+ '<p style="font-size: 14px; line-height: 1.8; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 25px; margin: 0;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed </p>'
+ '</div>'
+ '</div>'
+ '<!--[if mso]></td></tr></table><![endif]-->'
+ '<table cellpadding="0" cellspacing="0" class="social_icons" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td style="word-break: break-word; vertical-align: top; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="left" cellpadding="0" cellspacing="0" class="social_table" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-tspace: 0; mso-table-rspace: 0; mso-table-bspace: 0; mso-table-lspace: 0;" valign="top">'
+ '<tbody>'
+ '<tr align="left" style="vertical-align: top; display: inline-block; text-align: left;" valign="top">'
+ '<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 4px; padding-left: 0px;" valign="top"><a href="https://www.facebook.com/" target="_blank"><img alt="Facebook" height="32" src="images/facebook2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="Facebook" width="32"/></a></td>'
+ '<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 4px; padding-left: 0px;" valign="top"><a href="https://twitter.com/" target="_blank"><img alt="Twitter" height="32" src="images/twitter2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="Twitter" width="32"/></a></td>'
+ '<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 4px; padding-left: 0px;" valign="top"><a href="https://instagram.com/" target="_blank"><img alt="Instagram" height="32" src="images/instagram2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="Instagram" width="32"/></a></td>'
+ '<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 4px; padding-left: 0px;" valign="top"><a href="https://www.linkedin.com/" target="_blank"><img alt="LinkedIn" height="32" src="images/linkedin2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="LinkedIn" width="32"/></a></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<div style="background-color:transparent;">'
+ '<div class="block-grid" style="min-width: 320px; max-width: 700px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #e8edf3;">'
+ '<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e8edf3;">'
+ '<!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:transparent;"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:700px"><tr class="layout-full-width" style="background-color:#e8edf3"><![endif]-->'
+ '<!--[if (mso)|(IE)]><td align="center" width="700" style="background-color:#e8edf3;width:700px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;"><![endif]-->'
+ '<div class="col num12" style="min-width: 320px; max-width: 700px; display: table-cell; vertical-align: top; width: 700px;">'
+ '<div class="col_cont" style="width:100% !important;">'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">'
+ '<!--<![endif]-->'
+ '<table border="0" cellpadding="0" cellspacing="0" class="divider" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td class="divider_inner" style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">'
+ '<table align="center" border="0" cellpadding="0" cellspacing="0" class="divider_content" height="15" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 15px; width: 100%;" valign="top" width="100%">'
+ '<tbody>'
+ '<tr style="vertical-align: top;" valign="top">'
+ '<td height="15" style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" valign="top"><span></span></td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (!mso)&(!IE)]><!-->'
+ '</div>'
+ '<!--<![endif]-->'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '<!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->'
+ '</div>'
+ '</div>'
+ '</div>'
+ '<!--[if (mso)|(IE)]></td></tr></table><![endif]-->'
+ '</td>'
+ '</tr>'
+ '</tbody>'
+ '</table>'
+ '<!--[if (IE)]></div><![endif]-->'
+ '</body>'
+ '</html>'

module.exports = email